// <auto-generated />
namespace Democracy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _20160320 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20160320));
        
        string IMigrationMetadata.Id
        {
            get { return "201603201900578_20160320"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
